name: Build & publish project
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.15]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci && npm run build --if-present && npm run test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Multiple Docker Images to Heroku Apps
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          docker_compose_file: './docker-compose.yml'
          heroku_apps: '[{"imagename":"nginx-frontend","appname":"wefox-post-manager ","apptype":"web"}, {"imagename":"backend","appname":"wg-web-challenge ","apptype":"web"}]'
